export const cards = [
  {
    id: 1,
    title: "Handicraft Artwork",
    img: "../public/img/cat-artwork.jpg",
  },
  {
    id: 2,
    title: "Textile Creation",
    img: "../public/img/cat-textile.jpg",
  },
  {
    id: 3,
    title: "Home Decor",
    img: "../public/img/cat-home.jpg",
  },
  {
    id: 4,
    title: "Jewelry & Accessories",
    img: "../public/img/cat-jewelry.jpg",
  },
  {
    id: 5,
    title: "Wellness & Beauty",
   img: "../public/img/cat-beauty.jpg",
  },
  {
    id: 6,
    title: "Ceremonial Arts",
    img: "../public/img/cat-ceremonial.jpg",
  },
  {
    id: 7,
    title: "Educational Services",
    img: "../public/img/cat-educational.jpg",
  },
];

export const projects = [
  {
    id: 1,
    img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Handicraft art",
    username: "N. Nawarathne",
  },
  {
    id: 2,
    img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Handicraft art",
    username: "N. Nawarathne",
  },
  {
    id: 3,
    img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Handicraft art",
    username: "N. Nawarathne",
  },
  {
    id: 4,
    img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Handicraft art",
    username: "N. Nawarathne",
  },
  {
    id: 5,
    img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Handicraft art",
    username: "N. Nawarathne",
  },
  {
    id: 6,
    img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Handicraft art",
    username: "N. Nawarathne",
  },
  {
    id: 7,
    img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Handicraft art",
    username: "N. Nawarathne",
  },
  {
    id: 8,
    img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Handicraft art",
    username: "N. Nawarathne",
  },
];

export const gigs = [
  {
    id: 1,
    img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom jewelry based on your needs",
    price: 59,
    star: 5,
    username: "J. Rathnayake",
  },
  {
    id: 2,
     img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom jewelry based on your needs",
    price: 59,
    star: 5,
    username: "J. Rathnayake",
  },
  {
    id: 3,
     img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom jewelry based on your needs",
    price: 59,
    star: 5,
    username: "J. Rathnayake",
  },
  {
    id: 4,
     img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom jewelry based on your needs",
    price: 59,
    star: 5,
    username: "J. Rathnayake",
  },
  {
    id: 5,
     img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom jewelry based on your needs",
    price: 59,
    star: 5,
    username: "J. Rathnayake",
  },
  {
    id: 6,
     img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom jewelry based on your needs",
    price: 59,
    star: 5,
    username: "J. Rathnayake",
  },
  {
     img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom jewelry based on your needs",
    price: 59,
    star: 5,
    username: "J. Rathnayake",
  },
  {
     img: "../../public/img/testimg.jpg",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom jewelry based on your needs",
    price: 59,
    star: 5,
    username: "J. Rathnayake",
  },
];
